### ISSUE TITLE
whereNotIn... possible bug

### ISSUE THREAD

**Issue by cocosistemas** [sql2builder/sql2builder.github.io#15]
try this: https://sql2builder.github.io?base64sql=c2VsZWN0ICogZnJvbSBteVRhYmxlIHdoZXJlIG15S2V5RmllbGQgaW4gKHNlbGVjdCBteUtleUZpZWxkIGZyb20gbXlTZWNvbmRUYWJsZSB3aGVyZSBvdGhlcktleT0nYXNkYXNkJykgb3JkZXIgYnkgbXlLZXlGaWVsZA==

converts to whereNotIn and the sql has no .. SELECT ...NOT IN... 
I think that it must be whereIn
Thx

**Comment by liquid207** [comment]
Fixed, thank you for bring up this
