### ISSUE TITLE
Bug with Table Aliases

### ISSUE THREAD

**Issue by yusuftaufiq** [sql2builder/sql2builder.github.io#21]
I'm currently having trouble trying to convert SQL with table aliases. So with the following query:
```sql
select
	*
from
	purchase_order_headers poh
where
	not exists (
	select
		pr.id
	from
		purchase_requests pr
	where
		pr.purchase_order_header_id = poh.id)
```

I get results like the following code:
```php
DB::table('purchase_order_headers')
    ->select('*')
    ->whereNotExists(function ($query) {
        $query->from('purchase_requests')
            ->select('purchase_requests.id')
            ->where('purchase_requests.purchase_order_header_id','=',DB::raw('poh.id'));
    }
    ->get();
```

The problem is in `DB::raw('poh.id')`, so instead of getting `poh.id` it should be `purchase_order_headers.id`. Hope this can be fixed, and thanks for this awesome tool!

**Comment by liquid207** [comment]
Thanks for you bring this up, fixed.
