### ISSUE TITLE
can't do limits

### ISSUE THREAD

**Issue by widiarrohman1234** [sql2builder/sql2builder.github.io#23]
`SELECT pondok.no_pondok FROM pondok
ORDER BY pondok.id DESC
limit 1;`

`DB::table('pondok')
->select('pondok.no_pondok')
->orderBy('pondok.id','desc')
->get();`

it should be like this
`DB::table('pondok')
->select('pondok.no_pondok')
->orderBy('pondok.id','desc')
->limit(1)
->get();`

so much advice from me, thank you

**Comment by liquid207** [comment]
Fixed, thanks for your advice
